### ISSUE TITLE
`DOMINO_LOG_BACKUP_DIR` is created after using

### ISSUE THREAD

**Issue by stasjok** [nashcom/domino-startscript#8]
When `DOMINO_LOG_BACKUP_DIR` is set to some non-existent directory, it's created too late. The script first tries to move domino.log to it, but it gets an error. `check_create_directories` is called only later.

https://github.com/nashcom/domino-startscript/blob/cb349ffc67c00743acba762c700f0732719429d2/rc_domino_script#L2521-L2523

**Comment by Daniel-Nashed** [comment]
Oh nobody ran into this before. the directories should never change and you would probably not have the archive logs first.
but yes it makes sense to change the order. just made the change and pushed it also to the main branch. 
I am not currently working on a new release. I hope it is OK to pull down the update via git.

Because of dependencies with the Domino container project it will take a moment to align the changes there and test before I can make it a release.

**Comment by stasjok** [comment]
> just made the change and pushed it also to the main branch.
> I am not currently working on a new release. I hope it is OK to pull down the update via git.

It's OK. This problem surfaces itself only once and I've already changed the order locally manually. I just wanted it to be fixed in the next release, so my local changes don't get lost after update.
